alias: saleAnalytics
author: TEam Swift
link: http://ng-erp.com
document: http://ones_manual.mydoc.io/?t=35707
requirements:
    - crm
    - sale
    - marketing
    - analytics

auth_nodes:
    # 销售额统计
    - saleAnalytics.saleVolume.get
    # 销售排行
    - saleAnalytics.saleBoard.get

global_include:
    js:
        - apps/saleAnalytics/main
        - apps/saleAnalytics/model
        - apps/saleAnalytics/plugin

include:
    js:
        - apps/analytics/service
    css:
        - apps/analytics/statics/style

navs:
    Marketing:
        children:
            Sale Analytics:
                app: saleAnalytics
                children:
                    Sale Analytics:
                        app: saleAnalytics
                        icon: bar-chart
                        link: saleAnalytics/saleVolume
                    Sale Top Board:
                        app: saleAnalytics
                        icon: line-chart
                        link: saleAnalytics/saleBoard
