alias: printer
author: TEam Swift
link: http://ng-erp.com
requirements: 

auth_nodes:
    - printer.printTemplate.*

global_include:
    js:
        - apps/printer/service
i18n_global_loaded: true
navs:
    Base Data Set:
        children:
            Print Template:
                app: printer
                icon: print
                link: printer/printTemplate