alias: bpm
author: TEam Swift
link: http://ng-erp.com
document: http://ones_manual.mydoc.io/?t=35698
requirements:
    - product

auth_nodes:
    - bpm.workflow.*
    - bpm.workflowBuilder.put
auth_dont_need:
    - bpm.builder.get
    - bpm.workflowProgress.read

load_all_i18n: true
include:
    js:
        - apps/bpm/main
        - apps/bpm/model
        - apps/bpm/static/raphael-min
        - apps/bpm/static/flowchart
    css:
        - apps/bpm/static/style
global_include:
    js:
        - apps/bpm/model

navs:
    System Preference:
        children:
            BPM:
                app: bpm
                icon: retweet
                children:
                    Workflow:
                        app: bpm
                        icon: circle-o-notch
                        link: bpm/workflow