alias: smtp
author: TEam Swift
link: http://ng-erp.com
requirements:

auth_nodes:
    - smtp.send_mail.*

global_include:
    js:
        - apps/smtp/service

navs:
    Marketing:
        children:
            Marketing:
                children:
                    Marketing Email:
                        app: smtp
                        link: smtp/send_mail
