alias: dataModel
author: TEam Swift
description: ONES 数据模型模块
link: http://ng-erp.com
document: http://ones_manual.mydoc.io/?t=35693
auth_nodes:
    - dataModel.dataModelField.*
include:
    js:
        - apps/dataModel/main

load_all_i18n: true

navs:
    Base Data Set:
        children:
            System Common Data:
                children:
                    Data Model Field:
                        app: dataModel
                        link: dataModel/dataModelField