alias: purchase
author: TEam Swift
link: http://ng-erp.com
document: http://ones_manual.mydoc.io/?t=35701
requirements: 
    - product
    - store
    - supplier
    - bpm

auth_nodes:
    - purchase.purchase.*

load_modules:
    - ones.gridViewModule
    - ones.app.product.model

include:
    js:
        - apps/purchase/main
        - apps/purchase/model
        - apps/product/model
        - apps/supplier/model
global_include:
    js:
        - apps/purchase/plugin

navs:
    Purchase:
        app: purchase
        icon: shopping-cart
        children:
            Purchase:
                app: purchase
                icon: shopping-cart
                children:
                    Add New Purchase:
                        app: purchase
                        link: purchase/purchase/add/bill
                    Purchase Bills:
                        app: purchase
                        link: purchase/purchase
